# Generated by Django 4.0.4 on 2023-09-04 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('PA', 'Pantalones'), ('CAM', 'Camisas'), ('CAL', 'Calzado'), ('PLA', 'Playeras'), ('ACC', 'Accesorios')], max_length=3)),
                ('company', models.CharField(choices=[('CP', 'Cuidado con el perro'), ('MH', 'H&M'), ('GS', 'Guess'), ('F2', 'Forever 21'), ('PB', 'Pull & Bear')], default='AR', max_length=2)),
                ('label', models.CharField(choices=[('N', 'Nuevo'), ('V', 'Mas vendido'), ('T', 'Tendencia'), ('U', 'Ultimas Existencias')], max_length=2)),
                ('description', models.TextField()),
                ('indications', models.TextField(default='', max_length='700', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('cve_cat_producto', models.BigIntegerField(blank=True, null=True)),
                ('porcentaje_iva', models.IntegerField(blank=True, default=0, null=True)),
                ('porcentaje_ieps', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField(null=True)),
                ('num_pedido_ref', models.IntegerField(null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('ship_to', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('dispatched', models.BooleanField(default=False)),
                ('guia_envio', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('paqueteria', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('estatus_envio', models.CharField(blank=True, choices=[('A', 'Activo'), ('C', 'Cancelado'), ('R', 'Reembolso'), ('P', 'Proceso'), ('E', 'Enviado')], default='', max_length=50, null=True)),
                ('company', models.CharField(choices=[('CP', 'Cuidado con el perro'), ('MH', 'H&M'), ('GS', 'Guess'), ('F2', 'Forever 21'), ('PB', 'Pull & Bear')], default='AR', max_length=2)),
                ('entrega_estimada', models.DateField(blank=True, null=True)),
                ('costo_envio', models.FloatField(blank=True, null=True)),
                ('order_total', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_ref_id', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('payment_type', models.CharField(blank=True, max_length=30, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('porcentaje_iva', models.IntegerField(blank=True, default=0, null=True)),
                ('porcentaje_ieps', models.IntegerField(blank=True, default=0, null=True)),
                ('discount_price', models.FloatField(blank=True, default=0, null=True)),
                ('reference_price', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='nucleo.orderitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altDescription', models.TextField(max_length='100')),
                ('image', models.ImageField(null=True, upload_to='static/img/product')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.item')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(blank=True, max_length=100, null=True)),
                ('settlement_name', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('rfc', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_user_id', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
